url: https://fibrabike.github.io
baseurl: /

# Site settings
title: Fibra
email: info.fibrabike@gmail.com
description: "Fibrabike, le biciclette in legno fatte a mano in Italia per tutto il mondo"


# Team names, titles and social links
#people:
#- name: Matteo
#  pic: 1
#  position:
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #
#
#- name: Larry Parker
#  pic: 2
#  position: Lead Marketer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #
#
#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Fibrabike-104698780919352/
  - title: instagram
    url: https://www.instagram.com/fibrabike/

# Postal address (add as many lines as necessary)
address:
  - line: TESTER TESTER
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
